fifoget: fifoget.c
	@gcc -std=gnu90 fifoget.c -o fifoget

fifoskp: fifoskp.c
	@gcc -std=gnu90 fifoskp.c -o fifoskp

fiforev: fiforev.c
	@gcc -std=gnu90 fiforev.c -o fiforev

fifoply: fifoply.c
	@gcc -std=gnu90 fifoply.c -o fifoply
